import React, { createContext, useState, useContext, ReactNode } from "react";

// Define available languages
export type Language = "tr" | "en" | "ar" | "ru" | "zh" | "he" | "es";

// Define translations for each supported language
export const translations = {
  tr: {
    dashboard: "Panel",
    referrals: "Davetler",
    profile: "Profil",
    logout: "Çıkış",
    forwarderPanel: "Forwarder Paneli",
    welcomeDashboard: "Forwarder panelinize hoş geldiniz",
    totalEarnings: "Toplam Kazanç",
    fromAllTransactions: "Tüm işlemlerden",
    totalTransactions: "Toplam İşlemler",
    allProcessedTransactions: "Tüm işlenmiş işlemler",
    yourInviteCode: "Davet Kodunuz",
    shareWithClients: "Potansiyel müşterilerle paylaşın",
    transactionTypes: "İşlem Türleri",
    breakdownOfTypes: "İşlem türlerine göre dağılım",
    earningsPerType: "Tür Başına Kazanç",
    earningsBreakdown: "İşlem türüne göre kazanç dağılımı",
    purchase: "Alım",
    sale: "Satım",
    rental: "Kiralama",
    transactions: "işlem",
    transaction: "işlem",
    recentTransactions: "Son İşlemler",
    latestTransactions: "Son 5 işleminiz",
    date: "Tarih",
    userCompany: "Kullanıcı/Şirket",
    type: "Tür",
    earnings: "Kazanç",
    usingYourInviteCode: "Davet kodunuzu kullanarak",
    search: "Ara",
    details: "Detaylar",
    show: "Göster",
    hide: "Gizle",
    transactionHistory: "İşlem Geçmişi",
    noMatchingReferrals: "Eşleşen davet bulunamadı.",
    manageAccount: "Hesap ayarlarınızı ve tercihlerinizi yönetin",
    basicInformation: "Temel Bilgiler",
    security: "Güvenlik",
    profileUpdated: "Profil güncellendi",
    profileUpdateSuccess: "Profil bilgileriniz başarıyla güncellendi.",
    passwordUpdated: "Şifre güncellendi",
    passwordUpdateSuccess: "Şifreniz başarıyla değiştirildi.",
    firstName: "Ad",
    lastName: "Soyad",
    companyName: "Şirket Adı (İsteğe Bağlı)",
    emailAddress: "E-posta Adresi",
    phoneNumber: "Telefon Numarası",
    iban: "IBAN (Ödeme yatırmaları için)",
    saving: "Kaydediliyor...",
    saveChanges: "Değişiklikleri Kaydet",
    changePassword: "Şifre Değiştir",
    changePasswordDesc: "Hesabınızı güvende tutmak için şifrenizi güncelleyin",
    currentPassword: "Mevcut Şifre",
    newPassword: "Yeni Şifre",
    confirmPassword: "Yeni Şifreyi Onayla",
    changingPassword: "Şifre Değiştiriliyor...",
    updatePersonalInfo: "Kişisel ve iletişim bilgilerinizi güncelleyin"
  },
  en: {
    dashboard: "Dashboard",
    referrals: "Referrals",
    profile: "Profile",
    logout: "Logout",
    forwarderPanel: "Forwarder Panel",
    welcomeDashboard: "Welcome to your forwarder dashboard",
    totalEarnings: "Total Earnings",
    fromAllTransactions: "From all transactions",
    totalTransactions: "Total Transactions",
    allProcessedTransactions: "All processed transactions",
    yourInviteCode: "Your Invite Code",
    shareWithClients: "Share with potential clients",
    transactionTypes: "Transaction Types",
    breakdownOfTypes: "Breakdown of transaction types",
    earningsPerType: "Earnings Per Type",
    earningsBreakdown: "Earnings breakdown by transaction type",
    purchase: "Purchase",
    sale: "Sale",
    rental: "Rental",
    transactions: "transactions",
    transaction: "transaction",
    recentTransactions: "Recent Transactions",
    latestTransactions: "Your latest 5 transactions",
    date: "Date",
    userCompany: "User/Company",
    type: "Type",
    earnings: "Earnings",
    usingYourInviteCode: "Using your invite code",
    search: "Search",
    details: "Details",
    show: "Show",
    hide: "Hide",
    transactionHistory: "Transaction History",
    noMatchingReferrals: "No matching referrals found.",
    manageAccount: "Manage your account settings and preferences",
    basicInformation: "Basic Information",
    security: "Security",
    profileUpdated: "Profile updated",
    profileUpdateSuccess: "Your profile information has been updated successfully.",
    passwordUpdated: "Password updated",
    passwordUpdateSuccess: "Your password has been changed successfully.",
    firstName: "First Name",
    lastName: "Last Name",
    companyName: "Company Name (Optional)",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    iban: "IBAN (For payment deposits)",
    saving: "Saving...",
    saveChanges: "Save Changes",
    changePassword: "Change Password",
    changePasswordDesc: "Update your password to keep your account secure",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    changingPassword: "Changing Password...",
    updatePersonalInfo: "Update your personal and contact information"
  },
  ar: {
    dashboard: "لوحة القيادة",
    referrals: "الإحالات",
    profile: "الملف الشخصي",
    logout: "تسجيل خروج",
    forwarderPanel: "لوحة المرسل",
    welcomeDashboard: "مرحبًا بك في لوحة تحكم المُرسل",
    totalEarnings: "إجمالي الأرباح",
    fromAllTransactions: "من جميع المعاملات",
    totalTransactions: "إجمالي المعاملات",
    allProcessedTransactions: "جميع المعاملات المعالجة",
    yourInviteCode: "رمز الدعوة الخاص بك",
    shareWithClients: "شارك مع العملاء المحتملين",
    transactionTypes: "أنواع المعاملات",
    breakdownOfTypes: "تفصيل أنواع المعاملات",
    earningsPerType: "الأرباح لكل نوع",
    earningsBreakdown: "تفصيل الأرباح حسب نوع المعاملة",
    purchase: "شراء",
    sale: "بيع",
    rental: "تأجير",
    transactions: "معاملات",
    transaction: "معاملة",
    recentTransactions: "المعاملات الأخيرة",
    latestTransactions: "أحدث 5 معاملات لك",
    date: "التاريخ",
    userCompany: "المستخدم/الشركة",
    type: "النوع",
    earnings: "الأرباح",
    usingYourInviteCode: "باستخدام رمز الدعوة الخاص بك",
    search: "بحث",
    details: "تفاصيل",
    show: "عرض",
    hide: "إخفاء",
    transactionHistory: "سجل المعاملات",
    noMatchingReferrals: "لم يتم العثور على إحالات مطابقة.",
    manageAccount: "إدارة إعدادات وتفضيلات حسابك",
    basicInformation: "معلومات أساسية",
    security: "الأمان",
    profileUpdated: "تم تحديث الملف الشخصي",
    profileUpdateSuccess: "تم تحديث معلومات ملفك الشخصي بنجاح.",
    passwordUpdated: "تم تحديث كلمة المرور",
    passwordUpdateSuccess: "تم تغيير كلمة المرور بنجاح.",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    companyName: "اسم الشركة (اختياري)",
    emailAddress: "عنوان البريد الإلكتروني",
    phoneNumber: "رقم الهاتف",
    iban: "IBAN (للإيداعات النقدية)",
    saving: "جاري الحفظ...",
    saveChanges: "حفظ التغييرات",
    changePassword: "تغيير كلمة المرور",
    changePasswordDesc: "قم بتحديث كلمة المرور للحفاظ على أمان حسابك",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    changingPassword: "جاري تغيير كلمة المرور...",
    updatePersonalInfo: "تحديث المعلومات الشخصية ومعلومات الاتصال الخاصة بك"
  },
  ru: {
    dashboard: "Панель",
    referrals: "Рефералы",
    profile: "Профиль",
    logout: "Выход",
    forwarderPanel: "Панель экспедитора",
    welcomeDashboard: "Добро пожаловать в панель экспедитора",
    totalEarnings: "Общий доход",
    fromAllTransactions: "Со всех транзакций",
    totalTransactions: "Всего транзакций",
    allProcessedTransactions: "Все обработанные транзакции",
    yourInviteCode: "Ваш пригласительный код",
    shareWithClients: "Поделитесь с потенциальными клиентами",
    transactionTypes: "Типы транзакций",
    breakdownOfTypes: "Распределение типов транзакций",
    earningsPerType: "Доход по типам",
    earningsBreakdown: "Распределение дохода по типам транзакций",
    purchase: "Покупка",
    sale: "Продажа",
    rental: "Аренда",
    transactions: "транзакций",
    transaction: "транзакция",
    recentTransactions: "Недавние транзакции",
    latestTransactions: "Ваши последние 5 транзакции",
    date: "Дата",
    userCompany: "Пользователь/Компания",
    type: "Тип",
    earnings: "Доход",
    usingYourInviteCode: "С использованием вашего кода",
    search: "Поиск",
    details: "Детали",
    show: "Показать",
    hide: "Скрыть",
    transactionHistory: "История транзакций",
    noMatchingReferrals: "Совпадающие рефералы не найдены.",
    manageAccount: "Управляйте настройками и предпочтениями вашего аккаунта",
    basicInformation: "Основная информация",
    security: "Безопасность",
    profileUpdated: "Профиль обновлен",
    profileUpdateSuccess: "Информация вашего профиля успешно обновлена.",
    passwordUpdated: "Пароль обновлен",
    passwordUpdateSuccess: "Ваш пароль был успешно изменен.",
    firstName: "Имя",
    lastName: "Фамилия",
    companyName: "Название компании (Опционально)",
    emailAddress: "Адрес электронной почты",
    phoneNumber: "Номер телефона",
    iban: "IBAN (Для денежных переводов)",
    saving: "Сохранение...",
    saveChanges: "Сохранить изменения",
    changePassword: "Изменить пароль",
    changePasswordDesc: "Обновите пароль, чтобы обеспечить безопасность вашего аккаунта",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите новый пароль",
    changingPassword: "Изменение пароля...",
    updatePersonalInfo: "Обновите личную информацию и контактные данные"
  },
  zh: {
    dashboard: "仪表板",
    referrals: "推荐",
    profile: "个人资料",
    logout: "登出",
    forwarderPanel: "转发器面板",
    welcomeDashboard: "欢迎来到您的转发器仪表板",
    totalEarnings: "总收入",
    fromAllTransactions: "来自所有交易",
    totalTransactions: "总交易量",
    allProcessedTransactions: "所有已处理的交易",
    yourInviteCode: "您的邀请码",
    shareWithClients: "与潜在客户分享",
    transactionTypes: "交易类型",
    breakdownOfTypes: "交易类型明细",
    earningsPerType: "各类型收入",
    earningsBreakdown: "按交易类型的收入明细",
    purchase: "购买",
    sale: "销售",
    rental: "出租",
    transactions: "交易",
    transaction: "交易",
    recentTransactions: "最近交易",
    latestTransactions: "您最近的5笔交易",
    date: "日期",
    userCompany: "用户/公司",
    type: "类型",
    earnings: "收入",
    usingYourInviteCode: "使用您的邀请码",
    search: "搜索",
    details: "详情",
    show: "显示",
    hide: "隐藏",
    transactionHistory: "交易历史",
    noMatchingReferrals: "未找到匹配的推荐。",
    manageAccount: "管理您的账户设置和偏好",
    basicInformation: "基本信息",
    security: "安全",
    profileUpdated: "个人资料已更新",
    profileUpdateSuccess: "您的个人资料已成功更新。",
    passwordUpdated: "密码已更新",
    passwordUpdateSuccess: "您的密码已成功更改。",
    firstName: "名字",
    lastName: "姓氏",
    companyName: "公司名称（可选）",
    emailAddress: "电子邮件地址",
    phoneNumber: "电话号码",
    iban: "IBAN（用于付款存款）",
    saving: "保存中...",
    saveChanges: "保存更改",
    changePassword: "更改密码",
    changePasswordDesc: "更新您的密码以保持账户安全",
    currentPassword: "当前密码",
    newPassword: "新密码",
    confirmPassword: "确认新密码",
    changingPassword: "更改密码中...",
    updatePersonalInfo: "更新您的个人和联系信息"
  },
  he: {
    dashboard: "לוח מחוונים",
    referrals: "הפניות",
    profile: "פרופיל",
    logout: "התנתק",
    forwarderPanel: "לוח בקרה למשלח",
    welcomeDashboard: "ברוכים הבאים ללוח הבקרה שלכם",
    totalEarnings: "סך הכנסות",
    fromAllTransactions: "מכל העסקאות",
    totalTransactions: "סך כל העסקאות",
    allProcessedTransactions: "כל העסקאות המעובדות",
    yourInviteCode: "קוד ההזמנה שלך",
    shareWithClients: "שתף עם לקוחות פוטנציאליים",
    transactionTypes: "סוגי עסקאות",
    breakdownOfTypes: "פירוט סוגי העסקאות",
    earningsPerType: "הכנסות לפי סוג",
    earningsBreakdown: "פירוט הכנסות לפי סוג עסקה",
    purchase: "רכישה",
    sale: "מכירה",
    rental: "השכרה",
    transactions: "עסקאות",
    transaction: "עסקה",
    recentTransactions: "עסקאות אחרונות",
    latestTransactions: "5 העסקאות האחרונות שלך",
    date: "תאריך",
    userCompany: "משתמש/חברה",
    type: "סוג",
    earnings: "הכנסות",
    usingYourInviteCode: "באמצעות קוד ההזמנה שלך",
    search: "חיפוש",
    details: "פרטים",
    show: "הצג",
    hide: "הסתר",
    transactionHistory: "היסטוריית עסקאות",
    noMatchingReferrals: "לא נמצאו הפניות תואמות.",
    manageAccount: "נהל את הגדרות החשבון והעדפות שלך",
    basicInformation: "מידע בסיסי",
    security: "אבטחה",
    profileUpdated: "הפרופיל עודכן",
    profileUpdateSuccess: "המידע בפרופיל שלך עודכן בהצלחה.",
    passwordUpdated: "הסיסמה עודכנה",
    passwordUpdateSuccess: "הסיסמה שלך שונתה בהצלחה.",
    firstName: "שם פרטי",
    lastName: "שם משפחה",
    companyName: "שם החברה (אופציונלי)",
    emailAddress: "כתובת אימייל",
    phoneNumber: "מספר טלפון",
    iban: "IBAN (להפקדות תשלום)",
    saving: "שומר...",
    saveChanges: "שמור שינויים",
    changePassword: "שנה סיסמה",
    changePasswordDesc: "עדכן את הסיסמה שלך כדי לשמור על אבטחת החשבון שלך",
    currentPassword: "סיסמה נוכחית",
    newPassword: "סיסמה חדשה",
    confirmPassword: "אשר סיסמה חדשה",
    changingPassword: "משנה סיסמה...",
    updatePersonalInfo: "עדכן את המידע האישי ופרטי הקשר שלך"
  },
  es: {
    dashboard: "Panel",
    referrals: "Referencias",
    profile: "Perfil",
    logout: "Cerrar sesión",
    forwarderPanel: "Panel de Expedición",
    welcomeDashboard: "Bienvenido a su panel de expedición",
    totalEarnings: "Ingresos Totales",
    fromAllTransactions: "De todas las transacciones",
    totalTransactions: "Total de Transacciones",
    allProcessedTransactions: "Todas las transacciones procesadas",
    yourInviteCode: "Su Código de Invitación",
    shareWithClients: "Compartir con clientes potenciales",
    transactionTypes: "Tipos de Transacciones",
    breakdownOfTypes: "Desglose de tipos de transacciones",
    earningsPerType: "Ingresos por Tipo",
    earningsBreakdown: "Desglose de ingresos por tipo de transacción",
    purchase: "Compra",
    sale: "Venta",
    rental: "Alquiler",
    transactions: "transacciones",
    transaction: "transacción",
    recentTransactions: "Transacciones Recientes",
    latestTransactions: "Sus últimas 5 transacciones",
    date: "Fecha",
    userCompany: "Usuario/Empresa",
    type: "Tipo",
    earnings: "Ingresos",
    usingYourInviteCode: "Usando su código de invitación",
    search: "Buscar",
    details: "Detalles",
    show: "Mostrar",
    hide: "Ocultar",
    transactionHistory: "Historial de Transacciones",
    noMatchingReferrals: "No se encontraron referencias coincidentes.",
    manageAccount: "Administre la configuración y preferencias de su cuenta",
    basicInformation: "Información Básica",
    security: "Seguridad",
    profileUpdated: "Perfil actualizado",
    profileUpdateSuccess: "La información de su perfil ha sido actualizada con éxito.",
    passwordUpdated: "Contraseña actualizada",
    passwordUpdateSuccess: "Su contraseña ha sido cambiada con éxito.",
    firstName: "Nombre",
    lastName: "Apellido",
    companyName: "Nombre de la Empresa (Opcional)",
    emailAddress: "Correo Electrónico",
    phoneNumber: "Número de Teléfono",
    iban: "IBAN (Para depósitos de pago)",
    saving: "Guardando...",
    saveChanges: "Guardar Cambios",
    changePassword: "Cambiar Contraseña",
    changePasswordDesc: "Actualice su contraseña para mantener segura su cuenta",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Nueva Contraseña",
    changingPassword: "Cambiando Contraseña...",
    updatePersonalInfo: "Actualice su información personal y de contacto"
  }
};

// Create the language context
type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof translations.en) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Create a provider component
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Default language is Turkish
  const [language, setLanguage] = useState<Language>("tr");

  // Translation function
  const t = (key: keyof typeof translations.en) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Create a hook to use the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
